### ISSUE TITLE
Q wants larger negative limits for their users

### ISSUE THREAD

**Issue by DutcherNL** [DutcherNL/Scala-Dining-WebApp#108]
Q uses an incasso service within their association. They want to apply the dining costs to this incasso service as well which would mean that their users can rank up larger debts in the system

**Comment by mhvis** [comment]
I can see it being useful to allow unlimited debt for everyone, on the premise of having each association and not Scala responsible for incurring the debt that the users have with Scala. This is currently already the case according to the user agreement. In that case since it's not the responsibility of Scala we can allow it without too much risk for Scala :smirk_cat: and next to that give the associations more freedom in how the debt is settled. It's still possible to allow upgrading balance via other association treasurers since each transaction source and target is tracked, therefore it's possible to see for each association how much they need to credit from everyone and they can then do it however they like. Scala can see how much it should retrieve from each association. For Q it would probably mean that Q members don't need to do anything and their negative balance will be made in balance at the end of the year using direct debit, and if a member of a different association wants to upgrade via a Q treasurer, that would then be using cash and end up in the Q cashbox.

There would need to be good agreements from Scala on how and when Scala wants to incur the debt from the associations so that the associations can prepare.

Maybe there are still better solutions
