### ISSUE TITLE
Association pictures sometimes flash during loading

### ISSUE THREAD

**Issue by mhvis** [DutcherNL/Scala-Dining-WebApp#119]
Improvements:

* Reduce the image sizes, they're now huge (around 2000x1000 pixels each)
* Use `img` tag instead of CSS, that way they're loaded immediately and do not have to wait for the processing of CSS to start to begin loading.
* The images are currently not fully cached, they return the `Cache-Control: max-age=0` header. This should be improved in the nginx server settings.

**Comment by DutcherNL** [comment]
Association images in the assets folder was during initial set-up useful. Though now we are live (and copies are uploaded as well) they no longer service use. We can remove the entire association images folder. We can also (not through coding, just in the back-end) replace images of the associations to smaller sized images to fix the (legit) sizing problem.
The flashing btw I believe is caused due to the css file bing on a diffent server and thus sometimes have some loading delay, though I don't know if maintaining it locally will fix it.
I like the note on cashing the images, that's a good idea.

**Comment by mhvis** [comment]
I'm fine with removing the association images folder and what I meant by reducing the image sizes is uploading smaller versions in the admin panel, like you said (will do that sometime if you haven't already).

Using the `img` tag will make sure that we don't have to wait for the CSS to be loaded before the images start downloading, although impact is probably minor. I might change that in a PR.

Caching is already quite good with Nginx by default, it will return 304 Not Modified instead of the whole file when the file is the same as the locally cached version ([here's some info on that](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching)), I've set Cache-Control to 1 day now for /media/ and /static/ which will prevent the 304 roundtrips.
