### ISSUE TITLE
Dining list owners

### ISSUE THREAD

**Issue by mhvis** [DutcherNL/Scala-Dining-WebApp#130]
Request for change: instead of having a dining list claimer and a purchaser, have a list of dining list owners (or managers or claimers or whatever name suits best). These people would have all permissions on the dining list and can add and delete owners as well. That would remove the purchaser field in the dining list setting which may be confusing if the user doesn't know what it does. Next to that, Q often has 3 owners for each dining list: QookCie and 2 cooks, while it's now not possible to give multiple people permission to manage a dining list. It's also cleaner in code and also conceptually much easier for users to understand and make sure that the right people have enough permissions.

**Comment by DutcherNL** [comment]
I am not opposed to this, the problem here is however that the help stats are currently not updated without reloading the page itself thus having multple people that can change the stats will result in data conflicts as new post request might undo previous changes by other users. Thus this needs to be done before allowing multiple people to change either the shop/cook/clean stats or the pay stats.

As for why payment can be distributed, experience from the old Knights dining list has taught me that the owner of a dining list doesn't always pay for the dining list, thus I wanted that specefic task to be assigned to someone else.

**Comment by mhvis** [comment]
Oh ya that's a very good point :sunglasses: we should deal with that (shouldn't be hard). I understand for the need of the purchaser in the current situation. When multiple people can be owner we don't need that separate role anymore
